WITH elec_base AS (
    SELECT
        inn,
        report_date,
        arrears,
        payment,
        consumed_kwh,
        pay_per_kwh,
        arrears_lag1,
        payment_lag1,
        consumed_kwh_lag1,
        arrears_per_kwh,
        bill_per_kwh,
        implied_bill,
        arrears_to_payment,
        arrears_to_bill,
        pay_minus_bill_per_kwh,

    FROM elec_monthly_base
)

SELECT
    inn,
    arrears - arrears_lag1 AS elec_darrears_t,
    payment + (arrears - arrears_lag1) AS elec_implied_bill_t,
    payment / NULLIF(payment + (arrears - arrears_lag1),0) AS elec_coverage_t,
    payment / NULLIF(consumed_kwh,0) AS elec_pay_per_kwh_t,
    (payment + (arrears - arrears_lag1)) / NULLIF(consumed_kwh,0) AS elec_bill_per_kwh_t,
    arrears / NULLIF(consumed_kwh,0) AS elec_arrears_per_kwh_t,
    consumed_kwh AS elec_consumed_last_m1,
    AVG(consumed_kwh) OVER w_3m AS elec_consumed_avg_m3,
    MIN(consumed_kwh) OVER w_3m AS elec_consumed_min_m3,
    MAX(consumed_kwh) OVER w_3m AS elec_consumed_max_m3,
    APPROX_PERCENTILE(consumed_kwh, 0.5) OVER w_3m AS elec_consumed_median_m3,
    STDDEV(consumed_kwh) OVER w_3m AS elec_consumed_vol_m3,
    AVG(consumed_kwh) OVER w_6m AS elec_consumed_avg_m6,
    MIN(consumed_kwh) OVER w_6m AS elec_consumed_min_m6,
    MAX(consumed_kwh) OVER w_6m AS elec_consumed_max_m6,
    APPROX_PERCENTILE(consumed_kwh, 0.5) OVER w_6m AS elec_consumed_median_m6,
    STDDEV(consumed_kwh) OVER w_6m AS elec_consumed_vol_m6,
    AVG(consumed_kwh) OVER w_9m AS elec_consumed_avg_m9,
    MIN(consumed_kwh) OVER w_9m AS elec_consumed_min_m9,
    MAX(consumed_kwh) OVER w_9m AS elec_consumed_max_m9,
    APPROX_PERCENTILE(consumed_kwh, 0.5) OVER w_9m AS elec_consumed_median_m9,
    STDDEV(consumed_kwh) OVER w_9m AS elec_consumed_vol_m9,
    AVG(consumed_kwh) OVER w_12m AS elec_consumed_avg_m12,
    MIN(consumed_kwh) OVER w_12m AS elec_consumed_min_m12,
    MAX(consumed_kwh) OVER w_12m AS elec_consumed_max_m12,
    APPROX_PERCENTILE(consumed_kwh, 0.5) OVER w_12m AS elec_consumed_median_m12,
    STDDEV(consumed_kwh) OVER w_12m AS elec_consumed_vol_m12,
    (consumed_kwh - consumed_kwh_lag1) AS elec_consumed_mm_change,
    (consumed_kwh - consumed_kwh_lag1) / NULLIF(ABS(consumed_kwh_lag1),0) AS elec_consumed_mm_pct,
    AVG(consumed_kwh) OVER w_3m - AVG(consumed_kwh) OVER w_3m_lag AS elec_consumed_qq_change,
    (AVG(consumed_kwh) OVER w_3m - AVG(consumed_kwh) OVER w_3m_lag) / NULLIF(ABS(AVG(consumed_kwh) OVER w_3m_lag),0) AS elec_consumed_qq_pct,
    SUM(CASE WHEN consumed_kwh - LAG(consumed_kwh) OVER w_3m > 0 THEN 1 ELSE 0 END) OVER w_3m AS elec_consumed_pos_growth_cnt_m3,
    SUM(CASE WHEN consumed_kwh - LAG(consumed_kwh) OVER w_6m > 0 THEN 1 ELSE 0 END) OVER w_6m AS elec_consumed_pos_growth_cnt_m6,
    SUM(CASE WHEN consumed_kwh - LAG(consumed_kwh) OVER w_9m > 0 THEN 1 ELSE 0 END) OVER w_9m AS elec_consumed_pos_growth_cnt_m9,
    SUM(CASE WHEN consumed_kwh - LAG(consumed_kwh) OVER w_12m > 0 THEN 1 ELSE 0 END) OVER w_12m AS elec_consumed_pos_growth_cnt_m12,
    payment AS elec_payment_last_m1,
    AVG(payment) OVER w_3m AS elec_payment_avg_m3,
    MIN(payment) OVER w_3m AS elec_payment_min_m3,
    MAX(payment) OVER w_3m AS elec_payment_max_m3,
    APPROX_PERCENTILE(payment, 0.5) OVER w_3m AS elec_payment_median_m3,
    STDDEV(payment) OVER w_3m AS elec_payment_vol_m3,
    AVG(payment) OVER w_6m AS elec_payment_avg_m6,
    MIN(payment) OVER w_6m AS elec_payment_min_m6,
    MAX(payment) OVER w_6m AS elec_payment_max_m6,
    APPROX_PERCENTILE(payment, 0.5) OVER w_6m AS elec_payment_median_m6,
    STDDEV(payment) OVER w_6m AS elec_payment_vol_m6,
    AVG(payment) OVER w_9m AS elec_payment_avg_m9,
    MIN(payment) OVER w_9m AS elec_payment_min_m9,
    MAX(payment) OVER w_9m AS elec_payment_max_m9,
    APPROX_PERCENTILE(payment, 0.5) OVER w_9m AS elec_payment_median_m9,
    STDDEV(payment) OVER w_9m AS elec_payment_vol_m9,
    AVG(payment) OVER w_12m AS elec_payment_avg_m12,
    MIN(payment) OVER w_12m AS elec_payment_min_m12,
    MAX(payment) OVER w_12m AS elec_payment_max_m12,
    APPROX_PERCENTILE(payment, 0.5) OVER w_12m AS elec_payment_median_m12,
    STDDEV(payment) OVER w_12m AS elec_payment_vol_m12,
    payment - payment_lag1 AS elec_payment_mm_change,
    (payment - payment_lag1) / NULLIF(ABS(payment_lag1),0) AS elec_payment_mm_pct,
    AVG(payment) OVER w_3m - AVG(payment) OVER w_3m_lag AS elec_payment_qq_change,
    (AVG(payment) OVER w_3m - AVG(payment) OVER w_3m_lag) / NULLIF(ABS(AVG(payment) OVER w_3m_lag),0) AS elec_payment_qq_pct,
    SUM(CASE WHEN payment - LAG(payment) OVER w_3m > 0 THEN 1 ELSE 0 END) OVER w_3m AS elec_payment_pos_growth_cnt_m3,
    SUM(CASE WHEN payment - LAG(payment) OVER w_6m > 0 THEN 1 ELSE 0 END) OVER w_6m AS elec_payment_pos_growth_cnt_m6,
    SUM(CASE WHEN payment - LAG(payment) OVER w_9m > 0 THEN 1 ELSE 0 END) OVER w_9m AS elec_payment_pos_growth_cnt_m9,

        SUM(CASE WHEN payment - LAG(payment) OVER w_3m = 0 THEN 1 ELSE 0 END) OVER w_3m AS elec_payment_zero_cnt_m3,
    SUM(CASE WHEN payment - LAG(payment) OVER w_6m = 0 THEN 1 ELSE 0 END) OVER w_6m AS elec_payment_zero_cnt_m6,
    SUM(CASE WHEN payment - LAG(payment) OVER w_9m = 0 THEN 1 ELSE 0 END) OVER w_9m AS elec_payment_zero_cnt_m9,
    SUM(CASE WHEN payment - LAG(payment) OVER w_12m = 0 THEN 1 ELSE 0 END) OVER w_12m AS elec_payment_zero_cnt_m12,
    MAX(CASE WHEN payment = 0 THEN ROW_NUMBER() OVER w_12m ELSE 0 END) OVER w_12m AS elec_payment_zero_max_consec_m12,
    arrears AS elec_arrears_last_m1,
    AVG(arrears) OVER w_3m AS elec_arrears_avg_m3,
    MIN(arrears) OVER w_3m AS elec_arrears_min_m3,
    MAX(arrears) OVER w_3m AS elec_arrears_max_m3,
    APPROX_PERCENTILE(arrears, 0.5) OVER w_3m AS elec_arrears_median_m3,
    STDDEV(arrears) OVER w_3m AS elec_arrears_vol_m3,
    AVG(arrears) OVER w_6m AS elec_arrears_avg_m6,
    MIN(arrears) OVER w_6m AS elec_arrears_min_m6,
    MAX(arrears) OVER w_6m AS elec_arrears_max_m6,
    APPROX_PERCENTILE(arrears, 0.5) OVER w_6m AS elec_arrears_median_m6,
    STDDEV(arrears) OVER w_6m AS elec_arrears_vol_m6,
    AVG(arrears) OVER w_9m AS elec_arrears_avg_m9,
    MIN(arrears) OVER w_9m AS elec_arrears_min_m9,
    MAX(arrears) OVER w_9m AS elec_arrears_max_m9,
    APPROX_PERCENTILE(arrears, 0.5) OVER w_9m AS elec_arrears_median_m9,
    STDDEV(arrears) OVER w_9m AS elec_arrears_vol_m9,
    AVG(arrears) OVER w_12m AS elec_arrears_avg_m12,
    MIN(arrears) OVER w_12m AS elec_arrears_min_m12,
    MAX(arrears) OVER w_12m AS elec_arrears_max_m12,
    APPROX_PERCENTILE(arrears, 0.5) OVER w_12m AS elec_arrears_median_m12,
    STDDEV(arrears) OVER w_12m AS elec_arrears_vol_m12,
    (arrears - arrears_lag1) AS elec_arrears_trend_m12,
    AVG(arrears) OVER w_3_6m AS elec_arrears_avg_m3_6,
    AVG(arrears) OVER w_6_12m AS elec_arrears_avg_m6_12,
    ((arrears - arrears_lag1) * AVG(arrears) OVER w_3_6m) AS elec_arrears_trend_m6_x_avg_m3_6,
    ((arrears - arrears_lag1) * AVG(arrears) OVER w_6_12m) AS elec_arrears_trend_m12_x_avg_m6_12,
    (AVG(arrears) OVER w_6m) / NULLIF(STDDEV(arrears) OVER w_6m,0) AS elec_arrears_vol_adj_m6,
    (AVG(arrears) OVER w_9m) / NULLIF(STDDEV(arrears) OVER w_9m,0) AS elec_arrears_vol_adj_m9,
    (AVG(arrears) OVER w_12m) / NULLIF(STDDEV(arrears) OVER w_12m,0) AS elec_arrears_vol_adj_m12,
    (arrears - arrears_lag1) AS elec_arrears_mm_change,
    (arrears - arrears_lag1) / NULLIF(ABS(arrears_lag1),0) AS elec_arrears_mm_pct,
    AVG(arrears) OVER w_3m - AVG(arrears) OVER w_3m_lag AS elec_arrears_qq_change,
    (AVG(arrears) OVER w_3m - AVG(arrears) OVER w_3m_lag) / NULLIF(ABS(AVG(arrears) OVER w_3m_lag),0) AS elec_arrears_qq_pct,
    SUM(CASE WHEN arrears - LAG(arrears) OVER w_3m > 0 THEN 1 ELSE 0 END) OVER w_3m AS elec_arrears_pos_growth_cnt_m3,
    SUM(CASE WHEN arrears - LAG(arrears) OVER w_6m > 0 THEN 1 ELSE 0 END) OVER w_6m AS elec_arrears_pos_growth_cnt_m6,
    SUM(CASE WHEN arrears - LAG(arrears) OVER w_9m > 0 THEN 1 ELSE 0 END) OVER w_9m AS elec_arrears_pos_growth_cnt_m9,
    SUM(CASE WHEN arrears - LAG(arrears) OVER w_12m > 0 THEN 1 ELSE 0 END) OVER w_12m AS elec_arrears_pos_growth_cnt_m12,
    SUM(CASE WHEN arrears > 0 THEN 1 ELSE 0 END) OVER w_3m AS elec_arrears_gt0_cnt_m3,
    SUM(CASE WHEN arrears > 0 THEN 1 ELSE 0 END) OVER w_6m AS elec_arrears_gt0_cnt_m6,
    SUM(CASE WHEN arrears > 0 THEN 1 ELSE 0 END) OVER w_9m AS elec_arrears_gt0_cnt_m9,
    SUM(CASE WHEN arrears > 0 THEN 1 ELSE 0 END) OVER w_12m AS elec_arrears_gt0_cnt_m12,
    MAX(CASE WHEN arrears > 0 THEN ROW_NUMBER() OVER w_12m ELSE 0 END) OVER w_12m AS elec_arrears_gt0_max_consec_m12,
    MIN(CASE WHEN arrears = 0 THEN ROW_NUMBER() OVER w_12m END) AS elec_time_since_zero_arrears_m12,
    (arrears - arrears_lag1) AS elec_darrears_last_m1,
    AVG(arrears - arrears_lag1) OVER w_3m AS elec_darrears_avg_m3,
    MIN(arrears - arrears_lag1) OVER w_3m AS elec_darrears_min_m3,
    MAX(arrears - arrears_lag1) OVER w_3m AS elec_darrears_max_m3,
    APPROX_PERCENTILE(arrears - arrears_lag1, 0.5) OVER w_3m AS elec_darrears_median_m3,
    STDDEV(arrears - arrears_lag1) OVER w_3m AS elec_darrears_vol_m3,
    AVG(arrears - arrears_lag1) OVER w_6m AS elec_darrears_avg_m6,
    MIN(arrears - arrears_lag1) OVER w_6m AS elec_darrears_min_m6,
    MAX(arrears - arrears_lag1) OVER w_6m AS elec_darrears_max_m6,
    APPROX_PERCENTILE(arrears - arrears_lag1, 0.5) OVER w_6m AS elec_darrears_median_m6,
    STDDEV(arrears - arrears_lag1) OVER w_6m AS elec_darrears_vol_m6,
    AVG(arrears - arrears_lag1) OVER w_9m AS elec_darrears_avg_m9,
    MIN(arrears - arrears_lag1) OVER w_9m AS elec_darrears_min_m9,
    MAX(arrears - arrears_lag1) OVER w_9m AS elec_darrears_max_m9,
    APPROX_PERCENTILE(arrears - arrears_lag1, 0.5) OVER w_9m AS elec_darrears_median_m9,
    STDDEV(arrears - arrears_lag1) OVER w_9m AS elec_darrears_vol_m9,
    AVG(arrears - arrears_lag1) OVER w_12m AS elec_darrears_avg_m12,
    MIN(arrears - arrears_lag1) OVER w_12m AS elec_darrears_min_m12,
    MAX(arrears - arrears_lag1) OVER w_12m AS elec_darrears_max_m12,
    APPROX_PERCENTILE(arrears - arrears_lag1, 0.5) OVER w_12m AS elec_darrears_median_m12,
    STDDEV(arrears - arrears_lag1) OVER w_12m AS elec_darrears_vol_m12,
    (arrears - arrears_lag1) AS elec_darrears_trend_m12,
    (arrears - arrears_lag1) / NULLIF(ABS(arrears_lag1),0) AS elec_darrears_mm_pct,
    (AVG(arrears - arrears_lag1) OVER w_3m - AVG(arrears - arrears_lag1) OVER w_3m_lag) / NULLIF(ABS(AVG(arrears - arrears_lag1) OVER w_3m_lag),0) AS elec_darrears_qq_pct,
    SUM(CASE WHEN arrears - arrears_lag1 > 0 THEN 1 ELSE 0 END) OVER w_3m AS elec_darrears_pos_cnt_m3,
    SUM(CASE WHEN arrears - arrears_lag1 > 0 THEN 1 ELSE 0 END) OVER w_6m AS elec_darrears_pos_cnt_m6,
    SUM(CASE WHEN arrears - arrears_lag1 > 0 THEN 1 ELSE 0 END) OVER w_9m AS elec_darrears_pos_cnt_m9,
    SUM(CASE WHEN arrears - arrears_lag1 > 0 THEN 1 ELSE 0 END) OVER w_12m AS elec_darrears_pos_cnt_m12,
    MAX(CASE WHEN arrears - arrears_lag1 > 0 THEN ROW_NUMBER() OVER w_12m ELSE 0 END) OVER w_12m AS elec_darrears_pos_max_consec_m12,
    payment + (arrears - arrears_lag1) AS elec_bill_implied_last_m1,

    AVG(implied_bill) OVER w_3m AS elec_bill_implied_avg_m3,
    MIN(implied_bill) OVER w_3m AS elec_bill_implied_min_m3,
    MAX(implied_bill) OVER w_3m AS elec_bill_implied_max_m3,
    APPROX_PERCENTILE(implied_bill, 0.5) OVER w_3m AS elec_bill_implied_median_m3,
    STDDEV(implied_bill) OVER w_3m AS elec_bill_implied_vol_m3,
    AVG(implied_bill) OVER w_6m AS elec_bill_implied_avg_m6,
    MIN(implied_bill) OVER w_6m AS elec_bill_implied_min_m6,
    MAX(implied_bill) OVER w_6m AS elec_bill_implied_max_m6,
    APPROX_PERCENTILE(implied_bill, 0.5) OVER w_6m AS elec_bill_implied_median_m6,
    STDDEV(implied_bill) OVER w_6m AS elec_bill_implied_vol_m6,
    AVG(implied_bill) OVER w_9m AS elec_bill_implied_avg_m9,
    MIN(implied_bill) OVER w_9m AS elec_bill_implied_min_m9,
    MAX(implied_bill) OVER w_9m AS elec_bill_implied_max_m9,
    APPROX_PERCENTILE(implied_bill, 0.5) OVER w_9m AS elec_bill_implied_median_m9,
    STDDEV(implied_bill) OVER w_9m AS elec_bill_implied_vol_m9,
    AVG(implied_bill) OVER w_12m AS elec_bill_implied_avg_m12,
    MIN(implied_bill) OVER w_12m AS elec_bill_implied_min_m12,
    MAX(implied_bill) OVER w_12m AS elec_bill_implied_max_m12,
    APPROX_PERCENTILE(implied_bill, 0.5) OVER w_12m AS elec_bill_implied_median_m12,
    STDDEV(implied_bill) OVER w_12m AS elec_bill_implied_vol_m12,
    implied_bill - LAG(implied_bill) OVER w_6m AS elec_bill_implied_trend_m6,
    implied_bill - LAG(implied_bill) OVER w_12m AS elec_bill_implied_trend_m12,
    implied_bill - LAG(implied_bill) OVER w_1m AS elec_bill_implied_mm_change,
    (implied_bill - LAG(implied_bill) OVER w_1m) / NULLIF(ABS(LAG(implied_bill) OVER w_1m),0) AS elec_bill_implied_mm_pct,
    AVG(implied_bill) OVER w_3m - AVG(implied_bill) OVER w_3m_lag AS elec_bill_implied_qq_change,
    (AVG(implied_bill) OVER w_3m - AVG(implied_bill) OVER w_3m_lag) / NULLIF(ABS(AVG(implied_bill) OVER w_3m_lag),0) AS elec_bill_implied_qq_pct,
    SUM(CASE WHEN implied_bill - LAG(implied_bill) OVER w_3m > 0 THEN 1 ELSE 0 END) OVER w_3m AS elec_bill_implied_pos_growth_cnt_m3,
    SUM(CASE WHEN implied_bill - LAG(implied_bill) OVER w_6m > 0 THEN 1 ELSE 0 END) OVER w_6m AS elec_bill_implied_pos_growth_cnt_m6,
    SUM(CASE WHEN implied_bill - LAG(implied_bill) OVER w_9m > 0 THEN 1 ELSE 0 END) OVER w_9m AS elec_bill_implied_pos_growth_cnt_m9,
    SUM(CASE WHEN implied_bill - LAG(implied_bill) OVER w_12m > 0 THEN 1 ELSE 0 END) OVER w_12m AS elec_bill_implied_pos_growth_cnt_m12,
    SUM(CASE WHEN implied_bill <= 0 THEN 1 ELSE 0 END) OVER w_12m AS elec_bill_implied_le0_cnt_m12,
    coverage AS elec_coverage_last_m1,
    AVG(coverage) OVER w_3m AS elec_coverage_avg_m3,
    MIN(coverage) OVER w_3m AS elec_coverage_min_m3,
    MAX(coverage) OVER w_3m AS elec_coverage_max_m3,
    APPROX_PERCENTILE(coverage, 0.5) OVER w_3m AS elec_coverage_median_m3,
    STDDEV(coverage) OVER w_3m AS elec_coverage_vol_m3,
    AVG(coverage) OVER w_6m AS elec_coverage_avg_m6,
    MIN(coverage) OVER w_6m AS elec_coverage_min_m6,
    MAX(coverage) OVER w_6m AS elec_coverage_max_m6,
    APPROX_PERCENTILE(coverage, 0.5) OVER w_6m AS elec_coverage_median_m6,
    STDDEV(coverage) OVER w_6m AS elec_coverage_vol_m6,
    AVG(coverage) OVER w_9m AS elec_coverage_avg_m9,
    MIN(coverage) OVER w_9m AS elec_coverage_min_m9,
    MAX(coverage) OVER w_9m AS elec_coverage_max_m9,
    APPROX_PERCENTILE(coverage, 0.5) OVER w_9m AS elec_coverage_median_m9,
    STDDEV(coverage) OVER w_9m AS elec_coverage_vol_m9,
    AVG(coverage) OVER w_12m AS elec_coverage_avg_m12,
    MIN(coverage) OVER w_12m AS elec_coverage_min_m12,
    MAX(coverage) OVER w_12m AS elec_coverage_max_m12,
    APPROX_PERCENTILE(coverage, 0.5) OVER w_12m AS elec_coverage_median_m12,
    STDDEV(coverage) OVER w_12m AS elec_coverage_vol_m12,
    coverage - LAG(coverage) OVER w_6m AS elec_coverage_trend_m6,
    coverage - LAG(coverage) OVER w_12m AS elec_coverage_trend_m12,
    coverage - LAG(coverage) OVER w_1m AS elec_coverage_mm_change,
    (coverage - LAG(coverage) OVER w_1m) / NULLIF(ABS(LAG(coverage) OVER w_1m),0) AS elec_coverage_mm_pct,
    AVG(coverage) OVER w_3m - AVG(coverage) OVER w_3m_lag AS elec_coverage_qq_change,
    (AVG(coverage) OVER w_3m - AVG(coverage) OVER w_3m_lag) / NULLIF(ABS(AVG(coverage) OVER w_3m_lag),0) AS elec_coverage_qq_pct,
    SUM(payment) OVER w_3m / NULLIF(SUM(implied_bill) OVER w_3m,0) AS elec_collection_ratio_m3,
    SUM(payment) OVER w_6m / NULLIF(SUM(implied_bill) OVER w_6m,0) AS elec_collection_ratio_m6,
    SUM(payment) OVER w_9m / NULLIF(SUM(implied_bill) OVER w_9m,0) AS elec_collection_ratio_m9,
    SUM(payment) OVER w_12m / NULLIF(SUM(implied_bill) OVER w_12m,0) AS elec_collection_ratio_m12,
    SUM(CASE WHEN payment < implied_bill THEN 1 ELSE 0 END) OVER w_3m AS elec_underpay_cnt_m3,
    SUM(CASE WHEN payment < implied_bill THEN 1 ELSE 0 END) OVER w_6m AS elec_underpay_cnt_m6,
    SUM(CASE WHEN payment < implied_bill THEN 1 ELSE 0 END) OVER w_9m AS elec_underpay_cnt_m9,
    SUM(CASE WHEN payment < implied_bill THEN 1 ELSE 0 END) OVER w_12m AS elec_underpay_cnt_m12,
    MAX(CASE WHEN payment < implied_bill THEN ROW_NUMBER() OVER w_12m ELSE 0 END) OVER w_12m AS elec_underpay_max_consec_m12,
    SUM(CASE WHEN payment > implied_bill THEN 1 ELSE 0 END) OVER w_3m AS elec_overpay_cnt_m3,
    SUM(CASE WHEN payment > implied_bill THEN 1 ELSE 0 END) OVER w_6m AS elec_overpay_cnt_m6,
    SUM(CASE WHEN payment > implied_bill THEN 1 ELSE 0 END) OVER w_9m AS elec_overpay_cnt_m9,
    SUM(CASE WHEN payment > implied_bill THEN 1 ELSE 0 END) OVER w_12m AS elec_overpay_cnt_m12,
    payment / NULLIF(consumed_kwh,0) AS elec_pay_per_kwh_last_m1,
    AVG(payment / NULLIF(consumed_kwh,0)) OVER w_3m AS elec_pay_per_kwh_avg_m3,
    MIN(payment / NULLIF(consumed_kwh,0)) OVER w_3m AS elec_pay_per_kwh_min_m3,
    MAX(payment / NULLIF(consumed_kwh,0)) OVER w_3m AS elec_pay_per_kwh_max_m3,
    APPROX_PERCENTILE(payment / NULLIF(consumed_kwh,0), 0.5) OVER w_3m AS elec_pay_per_kwh_median_m3,
    STDDEV(payment / NULLIF(consumed_kwh,0)) OVER w_3m AS elec_pay_per_kwh_vol_m3,
    AVG(payment / NULLIF(consumed_kwh,0)) OVER w_6m AS elec_pay_per_kwh_avg_m6,
    MIN(payment / NULLIF(consumed_kwh,0)) OVER w_6m AS elec_pay_per_kwh_min_m6,
    MAX(payment / NULLIF(consumed_kwh,0)) OVER w_6m AS elec_pay_per_kwh_max_m6,
    APPROX_PERCENTILE(payment / NULLIF(consumed_kwh,0), 0.5) OVER w_6m AS elec_pay_per_kwh_median_m6,

    AVG(pay_per_kwh) OVER w_6m AS elec_pay_per_kwh_avg_m6,
    MIN(pay_per_kwh) OVER w_6m AS elec_pay_per_kwh_min_m6,
    MAX(pay_per_kwh) OVER w_6m AS elec_pay_per_kwh_max_m6,
    APPROX_PERCENTILE(pay_per_kwh, 0.5) OVER w_6m AS elec_pay_per_kwh_median_m6,
    STDDEV(pay_per_kwh) OVER w_6m AS elec_pay_per_kwh_vol_m6,

    AVG(pay_per_kwh) OVER w_9m AS elec_pay_per_kwh_avg_m9,
    MIN(pay_per_kwh) OVER w_9m AS elec_pay_per_kwh_min_m9,
    MAX(pay_per_kwh) OVER w_9m AS elec_pay_per_kwh_max_m9,
    APPROX_PERCENTILE(pay_per_kwh, 0.5) OVER w_9m AS elec_pay_per_kwh_median_m9,
    STDDEV(pay_per_kwh) OVER w_9m AS elec_pay_per_kwh_vol_m9,

    AVG(pay_per_kwh) OVER w_12m AS elec_pay_per_kwh_avg_m12,
    MIN(pay_per_kwh) OVER w_12m AS elec_pay_per_kwh_min_m12,
    MAX(pay_per_kwh) OVER w_12m AS elec_pay_per_kwh_max_m12,
    APPROX_PERCENTILE(pay_per_kwh, 0.5) OVER w_12m AS elec_pay_per_kwh_median_m12,
    STDDEV(pay_per_kwh) OVER w_12m AS elec_pay_per_kwh_vol_m12,

    -- Bill per kWh rolling features
    AVG(bill_per_kwh) OVER w_3m AS elec_bill_per_kwh_avg_m3,
    MIN(bill_per_kwh) OVER w_3m AS elec_bill_per_kwh_min_m3,
    MAX(bill_per_kwh) OVER w_3m AS elec_bill_per_kwh_max_m3,
    APPROX_PERCENTILE(bill_per_kwh, 0.5) OVER w_3m AS elec_bill_per_kwh_median_m3,
    STDDEV(bill_per_kwh) OVER w_3m AS elec_bill_per_kwh_vol_m3,

    AVG(bill_per_kwh) OVER w_6m AS elec_bill_per_kwh_avg_m6,
    MIN(bill_per_kwh) OVER w_6m AS elec_bill_per_kwh_min_m6,
    MAX(bill_per_kwh) OVER w_6m AS elec_bill_per_kwh_max_m6,
    APPROX_PERCENTILE(bill_per_kwh, 0.5) OVER w_6m AS elec_bill_per_kwh_median_m6,
    STDDEV(bill_per_kwh) OVER w_6m AS elec_bill_per_kwh_vol_m6,

    AVG(bill_per_kwh) OVER w_9m AS elec_bill_per_kwh_avg_m9,
    MIN(bill_per_kwh) OVER w_9m AS elec_bill_per_kwh_min_m9,
    MAX(bill_per_kwh) OVER w_9m AS elec_bill_per_kwh_max_m9,
    APPROX_PERCENTILE(bill_per_kwh, 0.5) OVER w_9m AS elec_bill_per_kwh_median_m9,
    STDDEV(bill_per_kwh) OVER w_9m AS elec_bill_per_kwh_vol_m9,

    AVG(bill_per_kwh) OVER w_12m AS elec_bill_per_kwh_avg_m12,
    MIN(bill_per_kwh) OVER w_12m AS elec_bill_per_kwh_min_m12,
    MAX(bill_per_kwh) OVER w_12m AS elec_bill_per_kwh_max_m12,
    APPROX_PERCENTILE(bill_per_kwh, 0.5) OVER w_12m AS elec_bill_per_kwh_median_m12,
    STDDEV(bill_per_kwh) OVER w_12m AS elec_bill_per_kwh_vol_m12,

    -- Arrears per kWh rolling features
    AVG(arrears_per_kwh) OVER w_3m AS elec_arrears_per_kwh_avg_m3,
    MIN(arrears_per_kwh) OVER w_3m AS elec_arrears_per_kwh_min_m3,
    MAX(arrears_per_kwh) OVER w_3m AS elec_arrears_per_kwh_max_m3,
    APPROX_PERCENTILE(arrears_per_kwh, 0.5) OVER w_3m AS elec_arrears_per_kwh_median_m3,
    STDDEV(arrears_per_kwh) OVER w_3m AS elec_arrears_per_kwh_vol_m3,

    AVG(arrears_per_kwh) OVER w_6m AS elec_arrears_per_kwh_avg_m6,
    MIN(arrears_per_kwh) OVER w_6m AS elec_arrears_per_kwh_min_m6,
    MAX(arrears_per_kwh) OVER w_6m AS elec_arrears_per_kwh_max_m6,
    APPROX_PERCENTILE(arrears_per_kwh, 0.5) OVER w_6m AS elec_arrears_per_kwh_median_m6,
    STDDEV(arrears_per_kwh) OVER w_6m AS elec_arrears_per_kwh_vol_m6,

    AVG(arrears_per_kwh) OVER w_9m AS elec_arrears_per_kwh_avg_m9,
    MIN(arrears_per_kwh) OVER w_9m AS elec_arrears_per_kwh_min_m9,
    MAX(arrears_per_kwh) OVER w_9m AS elec_arrears_per_kwh_max_m9,
    APPROX_PERCENTILE(arrears_per_kwh, 0.5) OVER w_9m AS elec_arrears_per_kwh_median_m9,
    STDDEV(arrears_per_kwh) OVER w_9m AS elec_arrears_per_kwh_vol_m9,

    AVG(arrears_per_kwh) OVER w_12m AS elec_arrears_per_kwh_avg_m12,
    MIN(arrears_per_kwh) OVER w_12m AS elec_arrears_per_kwh_min_m12,
    MAX(arrears_per_kwh) OVER w_12m AS elec_arrears_per_kwh_max_m12,
    APPROX_PERCENTILE(arrears_per_kwh, 0.5) OVER w_12m AS elec_arrears_per_kwh_median_m12,
    STDDEV(arrears_per_kwh) OVER w_12m AS elec_arrears_per_kwh_vol_m12,

    -- Arrears ratios
    AVG(arrears_to_payment) OVER w_3m AS elec_arrears_to_payment_avg_m3,
    AVG(arrears_to_payment) OVER w_6m AS elec_arrears_to_payment_avg_m6,
    AVG(arrears_to_payment) OVER w_9m AS elec_arrears_to_payment_avg_m9,
    AVG(arrears_to_payment) OVER w_12m AS elec_arrears_to_payment_avg_m12,

    AVG(arrears_to_bill) OVER w_3m AS elec_arrears_to_bill_avg_m3,
    AVG(arrears_to_bill) OVER w_6m AS elec_arrears_to_bill_avg_m6,
    AVG(arrears_to_bill) OVER w_9m AS elec_arrears_to_bill_avg_m9,
    AVG(arrears_to_bill) OVER w_12m AS elec_arrears_to_bill_avg_m12,

    -- Pay minus bill
    AVG(pay_minus_bill_per_kwh) OVER w_3m AS elec_pay_minus_bill_per_kwh_avg_m3,
    AVG(pay_minus_bill_per_kwh) OVER w_6m AS elec_pay_minus_bill_per_kwh_avg_m6,
    AVG(pay_minus_bill_per_kwh) OVER w_9m AS elec_pay_minus_bill_per_kwh_avg_m9,
    AVG(pay_minus_bill_per_kwh) OVER w_12m AS elec_pay_minus_bill_per_kwh_avg_m12
FROM elec_base
WINDOW
    w_3m AS (PARTITION BY inn ORDER BY report_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),
    w_6m AS (PARTITION BY inn ORDER BY report_date ROWS BETWEEN 5 PRECEDING AND CURRENT ROW),
    w_9m AS (PARTITION BY inn ORDER BY report_date ROWS BETWEEN 8 PRECEDING AND CURRENT ROW),
    w_12m AS (PARTITION BY inn ORDER BY report_date ROWS BETWEEN 11 PRECEDING AND CURRENT ROW),
    w_3m_lag AS (PARTITION BY inn ORDER BY report_date ROWS BETWEEN 5 PRECEDING AND 3 PRECEDING),
    w_3_6m AS (PARTITION BY inn ORDER BY report_date ROWS BETWEEN 6 PRECEDING AND 3 PRECEDING),
    w_6_12m AS (PARTITION BY inn ORDER BY report_date ROWS BETWEEN 12 PRECEDING AND 7 PRECEDING),
    w_1m AS (PARTITION BY inn ORDER BY report_date ROWS BETWEEN 1 PRECEDING AND CURRENT ROW);
